//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleActaProductos
    {
        public int idDetalleActaProductos { get; set; }
        public int idProducto { get; set; }
        public int IdActasProductosUsuarios { get; set; }
    
        public virtual ActasProductosUsuarios ActasProductosUsuarios { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
