//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventarioEntidadesDB : DbContext
    {
        public inventarioEntidadesDB()
            : base("name=inventarioEntidadesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActasProductosUsuarios> ActasProductosUsuarios { get; set; }
        public virtual DbSet<Caracteristicas> Caracteristicas { get; set; }
        public virtual DbSet<CatalogoProductos> CatalogoProductos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<DetalleActaProductos> DetalleActaProductos { get; set; }
        public virtual DbSet<DetalleProductos> DetalleProductos { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Modelos> Modelos { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<TipoCaracteristicas> TipoCaracteristicas { get; set; }
        public virtual DbSet<TipoDepartamentos> TipoDepartamentos { get; set; }
        public virtual DbSet<TipoOrigenes> TipoOrigenes { get; set; }
        public virtual DbSet<TipoProductos> TipoProductos { get; set; }
        public virtual DbSet<Ubicaciones> Ubicaciones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
    }
}
