//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.DetalleActaProductos = new HashSet<DetalleActaProductos>();
            this.DetalleProductos = new HashSet<DetalleProductos>();
        }
    
        public int idProducto { get; set; }
        public int idTipoOrigen { get; set; }
        public int idModelo { get; set; }
        public int idTipoProducto { get; set; }
        public string Nombre { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public string codigoSecob { get; set; }
        public string codigoFinazas { get; set; }
        public string ContratoAdquisicion { get; set; }
        public Nullable<decimal> CostoAdquisicion { get; set; }
        public string NumeroSerie { get; set; }
        public short Estado { get; set; }
        public string Observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleActaProductos> DetalleActaProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProductos> DetalleProductos { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual TipoOrigenes TipoOrigenes { get; set; }
        public virtual TipoProductos TipoProductos { get; set; }
    }
}
