//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.ActasProductosUsuarios = new HashSet<ActasProductosUsuarios>();
        }
    
        public int idUsuario { get; set; }
        public int idDepartamento { get; set; }
        public int idPerfil { get; set; }
        public int idUbicacion { get; set; }
        public string Usuario { get; set; }
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public string Extension { get; set; }
        public Nullable<short> Activar { get; set; }
        public string Observacion { get; set; }
        public string Contrasenia { get; set; }
        public string ConfirContrasenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasProductosUsuarios> ActasProductosUsuarios { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual Perfiles Perfiles { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
    }
}
